version: '3.8'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./input_data:/opt/spark/input_data
    - ./output_data:/opt/spark/output_data
    - ./generation:/opt/spark/generation
  networks:
    - airflow-network

x-airflow-common: &airflow-common
  image: airflow-custom-image
  extra_hosts:
      - "host.docker.internal:host-gateway"
  environment:
      - HDFS_NAMENODE=hdfs://host.docker.internal:9000
  env_file:
    - .airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./DAG:/opt/airflow/dags
    - ./input_data:/opt/airflow/input_data
    - ./input_data:/opt/spark/input_data
    - ./output_data:/opt/airflow/output_data
    - ./output_data:/opt/spark/output_data
    - ./generation:/opt/airflow/generation
  depends_on:
    - postgres
  networks:
    - airflow-network

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - airflow-network

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - airflow-network
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow-network

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - scheduler
    networks:
      - airflow-network

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Abraham --lastname Barrett --role Admin --email p.zavadskii@innopolis.university --password admin && airflow scheduler"

networks:
  airflow-network: