version: '3.8'



x-airflow-common: &airflow-common
  image: airflow-custom-image
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./DAG:/opt/airflow/DAG
    - ./input_data:/opt/airflow/input_data
    - ./output_data:/opt/airflow/output_data
    - ./generate:/opt/airflow/generate
  depends_on:
    - postgres
  networks:
    - airflow-network

services:
  spark-master:
    image: spark-custom-image
    container_name: spark-master
    command: >
      bash -c "
      tail -f /dev/null
      "
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./generation:/opt/spark/generation
      - ./input_data:/opt/spark/input_data
      - ./jobs:/opt/spark/jobs
    networks:
      - airflow-network

  spark-worker:
    image: spark-custom-image
    depends_on:
      - spark-master
    command: >
      bash -c "
      tail -f /dev/null
      "
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    volumes:
      - ./generation:/opt/spark/generation
      - ./input_data:/opt/spark/input_data
      - ./jobs:/opt/spark/jobs
    deploy:
      replicas: 2  
      
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow-network

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler
    networks:
      - airflow-network

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Abraham --lastname Barrett --role Admin --email p.zavadskii@innopolis.university --password admin && airflow scheduler"

networks:
  airflow-network: