name: CI for Data Generation

on:
  push:
    paths:
      - 'generation/main.go'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'generation/main.go'
      - '.github/workflows/ci.yml'

jobs:
  test-generation:
    name: Run Go generation tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Run go test
        working-directory: ./generation
        run: go test ./...

  check-remote:
    name: Check remote server environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Ping server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Server reachable!"

      - name: Check tools
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /root/ && git pull 2> /dev/null ;
          '

