name: CI for Data Generation

on:
  push:
    paths:
      - 'generation/main.go'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'generation/main.go'
      - '.github/workflows/ci.yml'

jobs:
  test-generation:
    name: Run Go generation tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Run go test
        working-directory: ./generation
        run: go test ./...

  check-remote:
    name: Check remote server environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Ping server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Server reachable!"

      - name: Check tools
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            echo "...Checking tools on server...";
            command -v go || echo "go not found!";
            go version || echo "go version check failed!";

            command -v python3 || echo "python3 not found";
            python3 --version || echo "python3 version check failed!";

            command -v pyspark || echo "pyspark not found!";
            pyspark --version || echo "pyspark version check failed!";

            command -v docker || echo "docker not found!";
            docker --version || echo "docker version check failed!";
          '

